spring:
  application:
    name: discovery-server
  cloud:
    config:
      profile: prod
  config:
    import: optional:configserver:http://localhost:8888





#server:
#  port: 8761
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#  instance:
#    hostname: discovery-server